const mongoose=require('mongoose');

//call for Main function;
main()
       .then(()=>{console.log("table is create ")})
             .catch((err)=>{console.log(err)});


//function to connect mongo Db to node
async function main(){
await mongoose.connect( 'mongodb://127.0.0.1:27017/placement');
}

//design schema for Detail Table
const placementSchema=mongoose.Schema({
  Roll_no: {
    type:String,
    required:true,
    unique:true
   },
  name:{
    type:String,
    required:true
  },
  year:{
    type :String,
    required:true
  },
  branch:{
    type:String,
    required:true
  },
  course:{
    type:String,
    required:true
  },
  company:{
    type:String,
    required:true
  }
})
placementSchema.index({ Roll_no: 1, name: 1, year: 1,branch:1, course:1,company:1 }, { unique: true });

const Detail= mongoose.model("Detail",placementSchema);

 const placementData = [
  
    { "name": "Aastha Sahu", "Roll_no": "207902", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Abhishek Jha", "Roll_no": "207903", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Genpact" },
    { "name": "Amit Jatola", "Roll_no": "207905", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Amit Tuti", "Roll_no": "207906", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Citi Bank" },
    { "name": "Amrit Pandey", "Roll_no": "207907", "year": "2023", "branch": "MCA", "course": "MCA", "company": "SAP Labs" },
    { "name": "Anmol Khandelwal", "Roll_no": "207908", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Genpact" },
    { "name": "Anwesha Das", "Roll_no": "207909", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Genpact" },
    { "name": "Ashish Patidar", "Roll_no": "207910", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Genpact" },
    { "name": "Ashiwini Bokade", "Roll_no": "207911", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Kagool" },
    { "name": "Ayaskanta Ghosh", "Roll_no": "207912", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Balkrishan Patidar", "Roll_no": "207913", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Briddhi Jaiswal", "Roll_no": "207915", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Deutsche Bank" },
    { "name": "Deepak Sahu", "Roll_no": "207916", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Genpact" },
    { "name": "Diksha Jain", "Roll_no": "207918", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Druva" },
    { "name": "Divyanshu Tyagi", "Roll_no": "207919", "year": "2023", "branch": "MCA", "course": "MCA", "company": "JPMC" },
    { "name": "Gaurav Raj", "Roll_no": "207921", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Kagool" },
    { "name": "Hariom Rajput", "Roll_no": "207923", "year": "2023", "branch": "MCA", "course": "MCA", "company": "MAQ Software" },
    { "name": "Jayant Verma", "Roll_no": "207924", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Radisys" },
    { "name": "Jaydeep Patidar", "Roll_no": "207925", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Genpact" },
    { "name": "Joydeep Dey", "Roll_no": "207926", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Arcesium" },
    { "name": "Kamesh Kewlani", "Roll_no": "207927", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Genpact" },
    { "name": "Kartik Patidar", "Roll_no": "207928", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Kundan Kumar", "Roll_no": "207929", "year": "2023", "branch": "MCA", "course": "MCA", "company": "ZL Technologies" },
    { "name": "Mahendra Singh Bora", "Roll_no": "207930", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Kubeangles" },
    { "name": "Mansi Sikarwar", "Roll_no": "207931", "year": "2023", "branch": "MCA", "course": "MCA", "company": "JPMC" },
    { "name": "Mileni Trivedi", "Roll_no": "207932", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Samsung Electronics" },
    { "name": "Nikita Shrivastav", "Roll_no": "207933", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Nirmal Dhakad", "Roll_no": "207934", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Nishika Gautam", "Roll_no": "207935", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Legato" },
    { "name": "Prabhat Singh Rajput", "Roll_no": "207936", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Pradumya Kumar", "Roll_no": "207937", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Kagool" },
    { "name": "Rajesh Lohar", "Roll_no": "207938", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Ravi Roshan Singh", "Roll_no": "207939", "year": "2023", "branch": "MCA", "course": "MCA", "company": "EXL" },
    { "name": "Riya Bisht", "Roll_no": "207940", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Genpact" },
    { "name": "Sachin Gaikwad", "Roll_no": "207941", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Shakshi", "Roll_no": "207942", "year": "2023", "branch": "MCA", "course": "MCA", "company": "CloudAngles" },
    { "name": "Sheetal Patil", "Roll_no": "207943", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Druva" },
    { "name": "Shidhanta Sen", "Roll_no": "207944", "year": "2023", "branch": "MCA", "course": "MCA", "company": "CloudAngles" },
    { "name": "Shivam Rathore", "Roll_no": "207945", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Shivani Mishra", "Roll_no": "207946", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Merilytics" },
    { "name": "Shreyansh Gupta", "Roll_no": "207947", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Genpact" },
    { "name": "Siddharth Kumar", "Roll_no": "207949", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Genpact" },
    { "name": "Soniya Dhakad", "Roll_no": "207950", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Vibhuti Chauhan", "Roll_no": "207951", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Vijay Vishvkarma", "Roll_no": "207952", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Vilas Admane", "Roll_no": "207953", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" },
    { "name": "Vishal Thakur", "Roll_no": "207954", "year": "2023", "branch": "MCA", "course": "MCA", "company": "Amdocs" }
  ,
  
  //   { "name": "Abhishek Mishra", "Roll_no": "21CSM1R01", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "NXP Semiconductors" },
  //   { "name": "Preety Rebari", "Roll_no": "21CSM1R18", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "Synopsys" },
  //   { "name": "Praveen Susundre", "Roll_no": "21CSM1R17", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "DP World" },
  //   { "name": "Lakshmi Vara Prasad B.", "Roll_no": "21CSM1R14", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "Qualcomm" },
  //   { "name": "Hritik Rastogi", "Roll_no": "21CSM1R11", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "Qualcomm" },
  //   { "name": "Eswar Kumar Kusumanchi", "Roll_no": "21CSM1R09", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "Qualcomm" },
  //   { "name": "Ritesh Kumar Jha", "Roll_no": "21CSM1R21", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "AMD" },
  //   { "name": "Ankit Shakya", "Roll_no": "21CSM1R04", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "Qualcomm" },
  //   { "name": "Shivani Toshniwal", "Roll_no": "21CSM1R23", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "Microsoft" },
  //   { "name": "Gajendra Saraswat", "Roll_no": "21CSM1R10", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "BNY Mellon" },
  //   { "name": "Ranjit Kumar Mahto", "Roll_no": "21CSM1R20", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "Qualcomm" },
  //   { "name": "Ayush Pandey", "Roll_no": "21CSM1R07", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "AMD" },
  //   { "name": "Aditya Billore", "Roll_no": "21CSM1R02", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "Micron" },
  //   { "name": "Suparna Bhattacharya", "Roll_no": "21CSM1R24", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "MBRDI" },
  //   { "name": "Vivek Kumar", "Roll_no": "21CSM1R26", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "AMD" },
  //   { "name": "Swati Verma", "Roll_no": "21CSM1R25", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "Natwest Group" },
  //   { "name": "Aditya Vasant Mhaske", "Roll_no": "21CSM1R03", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "Qualcomm" },
  //   { "name": "Indra Kishore Barman", "Roll_no": "21CSM1R12", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "OFSS" },
  //   { "name": "Arun Yadav", "Roll_no": "21CSM1R05", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "AMD" },
  //   { "name": "Sahil Chopra", "Roll_no": "21CSM1R22", "year": "2023", "branch": "MCA", "course": "M.Tech", "company": "Qualcomm" }
  // ,
  
  //   { "name": "Gayathri Magesh", "Roll_no": "197229", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Wells Fargo" },
  //   { "name": "Chaitanya Hardikar", "Roll_no": "197230", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Amazon" },
  //   { "name": "Harendra Bangra", "Roll_no": "197231", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "BNY Mellon" },
  //   { "name": "Himanshu Jain", "Roll_no": "197232", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Amdocs" },
  //   { "name": "Hrisheekesh Rajeev Kumar", "Roll_no": "197233", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Wells Fargo" },
  //   { "name": "Saikalyan Induri", "Roll_no": "197234", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Chronus" },
  //   { "name": "Ishita Gupta", "Roll_no": "197235", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "UBER" },
  //   { "name": "J Sushanth Reddy", "Roll_no": "197236", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Amazon" },
  //   { "name": "Jatavath Surya Prakash", "Roll_no": "197237", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Vodafone Idea limited" },
  //   { "name": "Joy Rakesh Chhajed", "Roll_no": "197238", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Qualcomm" },
  //   { "name": "Sai Ganesh Kasina", "Roll_no": "197241", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  //   { "name": "Keshav Ganesh", "Roll_no": "197242", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Amazon Web Services" },
  //   { "name": "Rahul Khatav", "Roll_no": "197243", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  //   { "name": "Kokkirala Rohith Rao", "Roll_no": "197244", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Providence" },
  //   { "name": "Akash Kothi", "Roll_no": "197245", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Morgan Stanley" },
  //   { "name": "Lakshita Choudhary", "Roll_no": "197246", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Schlumberger" },
  //   { "name": "Sai Bharath Reddy Lingala", "Roll_no": "197247", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Amazon" },
  //   { "name": "Maddisetty Venkatsai", "Roll_no": "197248", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "HONEYWELL" },
  //   { "name": "Maram Mahitha", "Roll_no": "197249", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  //   { "name": "Mohammad Jauwaad Shams", "Roll_no": "197250", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  //   { "name": "Muchipalli Abhishikth", "Roll_no": "197251", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Cogoport" },
  //   { "name": "Akshay Kumar Mundrathi", "Roll_no": "197252", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "PharmACE" },
  //   { "name": "Abhiram Nallamala", "Roll_no": "197253", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Mastercard" },
  //   { "name": "Naman Balai", "Roll_no": "197254", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  //   { "name": "Pravalika Narala", "Roll_no": "197255", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Wells Fargo" },
  //   { "name": "Neerudu Pavan Kalyan Reddy", "Roll_no": "197256", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Microsoft" },
  //   { "name": "Nemi Brahmachari", "Roll_no": "197257", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Service Now" },
  //   { "name": "Padmanabhuni Sindhusha", "Roll_no": "197258", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Microsoft" },
  //   { "name": "Manoj Kumar Reddy Peta", "Roll_no": "197259", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Amazon" },
  //   { "name": "Rithin Ponugoti", "Roll_no": "197260", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  //   { "name": "Prayag Patel", "Roll_no": "197261", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "D. E. Shaw" },
  //   { "name": "Priyanshu Khetan", "Roll_no": "197262", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  //   { "name": "Pulluri Nikitha", "Roll_no": "197263", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Uber" },
  //   { "name": "Racha Vinay Kumar", "Roll_no": "197264", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Zee5" },
  //   { "name": "Raghav Mukati", "Roll_no": "197265", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "BNY MELLON" },
  //   { "name": "ShreeRam Mohanty", "Roll_no": "197266", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Salesforce" },
  //   { "name": "Rajat Goyal", "Roll_no": "197267", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Microsoft" },
  //   { "name": "Bhargavi Ravirala", "Roll_no": "197268", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "HONEYWELL" },
  //   { "name": "Ashish Anand", "Roll_no": "197269", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Accenture" },
  //   { "name": "Ashish Anand", "Roll_no": "197270", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Accenture" }
  
  
  // { "name": "A.Anil Kumar", "Roll_no": "197101", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "C-DOT" },
  // { "name": "Aayush Garg", "Roll_no": "197102", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Qualcomm" },
  // { "name": "Abhishek Pratap Singh", "Roll_no": "197103", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Cashfree payments" },
  // { "name": "Adith", "Roll_no": "197104", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "SAP Labs" },
  // { "name": "Aditya Singh", "Roll_no": "197105", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Thoughtspot" },
  // { "name": "Aditya Joshi", "Roll_no": "197106", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "GEP Worldwide" },
  // { "name": "Aishwarya Nair", "Roll_no": "197107", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Rapido" },
  // { "name": "Akshat Dhiman", "Roll_no": "197108", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Deliveroo" },
  // { "name": "Aniket Dasurkar", "Roll_no": "197109", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  // { "name": "Anish Agarwal", "Roll_no": "197110", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "VISA" },
  // { "name": "Anubrata Seal", "Roll_no": "197111", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Pine Labs" },
  // { "name": "Archana Banothu", "Roll_no": "197112", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  // { "name": "Arpit Bohra", "Roll_no": "197113", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Pine Labs" },
  // { "name": "Sambasiva Reddy Asam", "Roll_no": "197114", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Citrix" },
  // { "name": "Ashish Anand", "Roll_no": "197115", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  // { "name": "Ayush Agrawal", "Roll_no": "197116", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "John Deere" },
  // { "name": "B Santosh Kumar", "Roll_no": "197118", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Qualcomm" },
  // { "name": "Sreyas Bekkam", "Roll_no": "197119", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Providence Health Care" },
  // { "name": "Bhoomika Chawan", "Roll_no": "197120", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Bharat Electronic Limited" },
  // { "name": "Manoj Boganadham", "Roll_no": "197121", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Goldman Sachs" },

    // { "name": "Chandrapal Baghel", "Roll_no": "197122", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
    // { "name": "Suma", "Roll_no": "197124", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Microsoft" },
    // { "name": "Deekshita Tirumala", "Roll_no": "197125", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Microsoft" },
    // { "name": "Deepanshu Jindal", "Roll_no": "197126", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Microsoft" },
    // { "name": "Disha Inwati", "Roll_no": "197127", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Microsoft" },
    // { "name": "Yasaswi Gadde", "Roll_no": "197128", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Morgan Stanley" },
    // { "name": "Gattukindi Shiva Teja", "Roll_no": "197129", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Samsung" },
    // { "name": "Govind Rathore", "Roll_no": "197130", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
    // { "name": "Chinmay Hardikar", "Roll_no": "197131", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Microsoft" },
    // { "name": "Harshit Bansal", "Roll_no": "197132", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Cashfree" },
    // { "name": "Himanshu Sah", "Roll_no": "197133", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Amazon Web Services" },
    // { "name": "Shantanu Sahadev Humbe", "Roll_no": "197134", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Goldman Sachs" },
    // { "name": "Jaswanth Inukonda", "Roll_no": "197135", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Here Technologies" },
    // { "name": "J Abhishek", "Roll_no": "197136", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Pine Labs" },
    // { "name": "Jaspreet Singh Saini", "Roll_no": "197137", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Servicenow" },
    // { "name": "Kadali Sai Vivek", "Roll_no": "197139", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Qualcomm" },
    // { "name": "K Vasantha", "Roll_no": "197140", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Cogoport" },
    // { "name": "Kashi Sharma", "Roll_no": "197141", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Salesforce" },
    // { "name": "Katta Omkar", "Roll_no": "197142", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Rapido" },
    // { "name": "Khambhampati Jaswanth", "Roll_no": "197143", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Strandlite" },
    //   { "name": "Komal", "Roll_no": "197144", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Microsoft" },
    //   { "name": "Koushik", "Roll_no": "197145", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
    //   { "name": "Madhusree Kundu", "Roll_no": "197146", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Zerodha" },
    //   { "name": "Manas Choudhury", "Roll_no": "197147", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Bharat Biotech" },
    //   { "name": "Madhusree", "Roll_no": "197148", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Qualcomm" },
    //   { "name": "Niharika", "Roll_no": "197149", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Amazon Web Services" },
    //   { "name": "Niranjan Kumar", "Roll_no": "197150", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Goldman Sachs" },
    //   { "name": "Pooja K", "Roll_no": "197151", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Sprinklr" },
    //   { "name": "Nivedita", "Roll_no": "197152", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Qualcomm" },
    //   { "name": "Pritish", "Roll_no": "197153", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Rakuten" },
    //   { "name": "Ravi Teja V", "Roll_no": "197154", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Amazon Web Services" },
    //   { "name": "Raviteja", "Roll_no": "197155", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "SAP Labs" },
    //   { "name": "Shivani G", "Roll_no": "197156", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Qualcomm" },
    //   { "name": "Rupesh", "Roll_no": "197157", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "ServiceNow" },
    //   { "name": "Rohith N", "Roll_no": "197158", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Citi" },
    //   { "name": "Sahil", "Roll_no": "197159", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Citi" },
    //   { "name": "Sandy", "Roll_no": "197160", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "ZS Associates" },
    //   { "name": "Saurabh S", "Roll_no": "197161", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Citi" },
    //   { "name": "Sayantan", "Roll_no": "197162", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Qualcomm" },
    //   { "name": "Shubham", "Roll_no": "197163", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Qualcomm" },
    //   { "name": "Shweta K", "Roll_no": "197164", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
    //   { "name": "Shreya", "Roll_no": "197165", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Microsoft" },
    //   { "name": "Srinivas", "Roll_no": "197166", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "SAP Labs" },
    //   { "name": "Sushant", "Roll_no": "197167", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "F5 Networks" },
    //   { "name": "Srinivas", "Roll_no": "197168", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Tata Consultancy Services" },
    //   { "name": "Teja", "Roll_no": "197169", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Qualcomm" }
    
    
  //     { "name": "Sidda Parthiv Reddy", "Roll_no": "197177", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  //     { "name": "Soumyadip Payra", "Roll_no": "197178", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "suki.ai" },
  //     { "name": "Sunny Singariya", "Roll_no": "197180", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  //     { "name": "Swarna Sweth", "Roll_no": "197181", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Schneider Electric" },
  //     { "name": "Tanisha Agrawal", "Roll_no": "197182", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Publicis sapient" },
  //     { "name": "Tejavath Venkat Sai Naik", "Roll_no": "197183", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Amazon" },
  //     { "name": "Shiva Shankar Vaddepally", "Roll_no": "197185", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Citrix" },
  //     { "name": "Ankit Reddy Vanguru", "Roll_no": "197186", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Samsung" },
  //     { "name": "Vedant Gandhi", "Roll_no": "197187", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "ServiceNow" },
  //     { "name": "Vishwas Gajawada", "Roll_no": "197188", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Microsoft" },
  //     { "name": "Yash Kumawat", "Roll_no": "197189", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "VISA" },
  //     { "name": "Yashpal Rajput", "Roll_no": "197190", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Goldman Sachs" },
  //     { "name": "Ranil Bala", "Roll_no": "197117", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Colgate Palmolive" },
  //     { "name": "Aashi Agrawal", "Roll_no": "197201", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Goldman Sachs" },
  //     { "name": "Abhinav Godara", "Roll_no": "197202", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "JOHN DEERE" },
  //     { "name": "Adarsh Reddy Muthyala", "Roll_no": "197203", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  //     { "name": "Aditya Kumar Sharma", "Roll_no": "197204", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Wells Fargo" },
  //     { "name": "Aditya Srivastav", "Roll_no": "197205", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Salesforce" },
  //     { "name": "Ahana Panja", "Roll_no": "197206", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "MasterCard" },
  //     { "name": "Akhil Vardhan Mallipeddu", "Roll_no": "197207", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Cloudangles" },
  //     { "name": "Alok Kushwaha", "Roll_no": "197208", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "deliveroo" },
  //     { "name": "Aniket Singh", "Roll_no": "197209", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Qualcomm" },
  //     { "name": "Ankit Kumar Gond", "Roll_no": "197210", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Samsung" },
  //     { "name": "Apurv Jain", "Roll_no": "197211", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Goldman Sachs" },
  //     { "name": "Ramakrishna Reddy Are", "Roll_no": "197212", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "DP World" },
  //     { "name": "Aryan Karki", "Roll_no": "197213", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "John Deere" },
  //     { "name": "Ashiqa Rahman", "Roll_no": "197214", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Amazon" },
  //     { "name": "Ashutosh Chandra", "Roll_no": "197215", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "SRI-B (Samsung)" },
  //     { "name": "Ayush Singhal", "Roll_no": "197216", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  //     { "name": "Bachu SaiPreetham", "Roll_no": "197217", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  //     { "name": "B. Sathwik Reddy", "Roll_no": "197218", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Yubi" },
  //     { "name": "Bharath Chaitanya Konkati", "Roll_no": "197219", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Honeywell" },
  //     { "name": "Suchith Reddy", "Roll_no": "197220", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Amazon" },
  //     { "name": "Chandana Sinderikeri", "Roll_no": "197221", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Qualcomm" },
  //     { "name": "Chinmay Joshi", "Roll_no": "197222", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Wells Fargo" },
  //     { "name": "Darshan Solanki", "Roll_no": "197223", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Visa" },
  //     { "name": "Satwika", "Roll_no": "197224", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "SAP labs" },
  //     { "name": "Deepak Prasad", "Roll_no": "197225", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Goldman Sachs" },
  //     { "name": "Devansh Ahuja", "Roll_no": "197226", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Mastercard" },
  //     { "name": "Gaddam Abhinav Reddy", "Roll_no": "197227", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "Oracle" },
  //     { "name": "Sowmya sri pravallika Gadi", "Roll_no": "197228", "year": "2023", "branch": "MCA", "course": "B.Tech", "company": "DELL" }
    
    
   
  
  // //   { "name": "D Chandra Shekhar", "Roll_no": "21CHM1R01", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "Pharma ACE" },
  //   { "name": "Debom Bhattacherjee", "Roll_no": "21CHM1R02", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "Tata Motors" },
  //   { "name": "Deepanshu Kishnani", "Roll_no": "21CHM1R03", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "PWC" },
  //   { "name": "Vattikuti Harica", "Roll_no": "21CHM1R06", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "L&T" },
  //   { "name": "Madhuri Kadali", "Roll_no": "21CHM1R07", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "Tata Motors" },
  //   { "name": "Pranay Prabhakar Mohadikar", "Roll_no": "21CHM1R10", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "Simerics" },
  //   { "name": "Prince Dangi", "Roll_no": "21CHM1R11", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "PWC" },
  //   { "name": "Ritika Pathania", "Roll_no": "21CHM1R12", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "PWC" },
  //   { "name": "Rohith Sudarshan P", "Roll_no": "21CHM1R14", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "PWC" },
  //   { "name": "Bramhanapalli Snehapriya", "Roll_no": "21CHM1R15", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "Reliance Retail" },
  //   { "name": "Tanmay Paul", "Roll_no": "21CHM1R16", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "Biocon" },
  //   { "name": "Kurapati Rithima", "Roll_no": "21CHM1S21", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "Reliance Retail" },
  //   { "name": "Dhrumil Khatri", "Roll_no": "21CHM2R04", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "Mahindra and Mahindra" },
  //   { "name": "Mustakim Shaikh", "Roll_no": "21CHM2R07", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "Mercedes Benz" },
  //   { "name": "Palash Dahake", "Roll_no": "21CHM2R08", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "Chetak Technology Limited" },
  //   { "name": "Pendem Shiva Nagaraju", "Roll_no": "21CHM2R09", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "Mercedes Benz" },
  //   { "name": "Shubham Das", "Roll_no": "21CHM2R11", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "PWC" },
  //   { "name": "Siddhartha Das", "Roll_no": "21CHM2R12", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "Akash Byjus" },
  //   { "name": "Aakriti Shrivastava", "Roll_no": "21CHM2S13", "year": "2023", "branch": "Chemical", "course": "M.Tech", "company": "Johnson Matthey" }
  // ,
  
    // { "name": "Abdul Khaliq", "Roll_no": "196101", "year": "2023", "branch": "Chemical", "course": "B.Tech", "company": "Cogoport" },
    // { "name": "Abhishek", "Roll_no": "196201", "year": "2023", "branch": "Chemical", "course": "B.Tech", "company": "Samagra" },
    // { "name": "Abhishek Sahu", "Roll_no": "196102", "year": "2023", "branch": "Chemical", "course": "B.Tech", "company": "Apollo 24/7" },
    // { "name": "Addanki Hemaswi", "Roll_no": "196202", "year": "2023", "branch": "Chemical", "course": "B.Tech", "company": "Wipro" },
    // { "name": "Akkineapally Anurag", "Roll_no": "196104", "year": "2023", "branch": "Chemical", "course": "B.Tech", "company": "Leoforce" },
    // { "name": "Akshay Patidar", "Roll_no": "196204", "year": "2023", "branch": "Chemical", "course": "B.Tech", "company": "Reliance Industries" },
    // { "name": "Akula Yeshwanth", "Roll_no": "196105", "year": "2023", "branch": "Chemical", "course": "B.Tech", "company": "Brane Enterprises" },
    // { "name": "Ameen", "Roll_no": "196141", "year": "2023", "branch": "Chemical", "course": "B.Tech", "company": "Blend 360" },
    // { "name": "Ankit Anthony Tirkey", "Roll_no": "196106", "year": "2023", "branch": "Chemical", "course": "B.Tech", "company": "TCS" },
    // { "name": "Anushka Singh", "Roll_no": "196107", "year": "2023", "branch": "Chemical", "course": "B.Tech", "company": "Oracle" }
  
  
  
   
  
    // { "name": "Aadesh", "Roll_no": "ECE01", "year": "2023", "branch": "MME", "course": "BTech", "company": "HDFC" },
    // { "name": "Anandh Reddy", "Roll_no": "ECE04", "year": "2023", "branch": "MME", "course": "BTech", "company": "SLB" },
    // { "name": "Anurag Rai", "Roll_no": "ECE06", "year": "2023", "branch": "MME", "course": "BTech", "company": "JIO" },
    // { "name": "Raviteja Badugu", "Roll_no": "ECE07", "year": "2023", "branch": "MME", "course": "BTech", "company": "IQVIA" },
    // { "name": "Boddula Sankeerthana", "Roll_no": "ECE08", "year": "2023", "branch": "MME", "course": "BTech", "company": "FRACTAL" },
    // { "name": "Chaganty Balaji", "Roll_no": "ECE10", "year": "2023", "branch": "MME", "course": "BTech", "company": "EXXONMOBIL" },
    // { "name": "Jayanth Chintapalli", "Roll_no": "ECE13", "year": "2023", "branch": "MME", "course": "BTech", "company": "SPRINKLR" },
    // { "name": "Devanshu", "Roll_no": "ECE14", "year": "2023", "branch": "MME", "course": "BTech", "company": "VESUVIUS" },
    // { "name": "Jaswanth Dhulipudi", "Roll_no": "ECE15", "year": "2023", "branch": "MME", "course": "BTech", "company": "ZEE" },
    // { "name": "Sandeep Kumar", "Roll_no": "ECE16", "year": "2023", "branch": "MME", "course": "BTech", "company": "COGOPORT" },
    // { "name": "Galanki Prajwalitha", "Roll_no": "ECE19", "year": "2023", "branch": "MME", "course": "BTech", "company": "EXL" },
    // { "name": "Ashish Gudise", "Roll_no": "ECE22", "year": "2023", "branch": "MME", "course": "BTech", "company": "ICICI" },
    // { "name": "Jaya Chandhra Gujjala", "Roll_no": "ECE24", "year": "2023", "branch": "MME", "course": "BTech", "company": "O9 SOLUTIONS" },
    // { "name": "Hema Varshini", "Roll_no": "ECE25", "year": "2023", "branch": "MME", "course": "BTech", "company": "GANIT" },
    // { "name": "Shravya Reddy Kontham", "Roll_no": "ECE27", "year": "2023", "branch": "MME", "course": "BTech", "company": "QUNATIPHI ANALYTICS" },
    // { "name": "Kakumanu Abhishek", "Roll_no": "ECE29", "year": "2023", "branch": "MME", "course": "BTech", "company": "IMPACT ANALYTICS" },
    // { "name": "Kashmira Kudche", "Roll_no": "ECE30", "year": "2023", "branch": "MME", "course": "BTech", "company": "INFINITY LEARN" },
    // { "name": "Keshav Bang", "Roll_no": "ECE32", "year": "2023", "branch": "MME", "course": "BTech", "company": "SPRINKLR" },
    // { "name": "Rupesh", "Roll_no": "ECE35", "year": "2023", "branch": "MME", "course": "BTech", "company": "RELIANCE INDUSTRIES" },
    // { "name": "Tarun", "Roll_no": "ECE36", "year": "2023", "branch": "MME", "course": "BTech", "company": "VEDANTA INDUSTRIES" },
    // { "name": "Maradana Kushal Kumar", "Roll_no": "ECE38", "year": "2023", "branch": "MME", "course": "BTech", "company": "LEOFORCE" },
    // { "name": "Merugu Vinay", "Roll_no": "ECE40", "year": "2023", "branch": "MME", "course": "BTech", "company": "INFINITY LEARN" },
    // { "name": "Aurbindo", "Roll_no": "ECE42", "year": "2023", "branch": "MME", "course": "BTech", "company": "VEDANTA INDUSTRIES" },
    // { "name": "Anusha Reddy", "Roll_no": "ECE43", "year": "2023", "branch": "MME", "course": "BTech", "company": "EXL" },
    // { "name": "Veerendhar", "Roll_no": "ECE47", "year": "2023", "branch": "MME", "course": "BTech", "company": "GLOBAL HITACHI" },
    // { "name": "Lokesh Pasumarthi", "Roll_no": "ECE48", "year": "2023", "branch": "MME", "course": "BTech", "company": "EXCELLENSIA" },
    // { "name": "Kamlesh Prajapati", "Roll_no": "ECE50", "year": "2023", "branch": "MME", "course": "BTech", "company": "JIO" },
    // { "name": "Pratik Kumar Keshri", "Roll_no": "ECE51", "year": "2023", "branch": "MME", "course": "BTech", "company": "ACCENTURE" },
    // { "name": "Shree Chandhan Reddy", "Roll_no": "ECE52", "year": "2023", "branch": "MME", "course": "BTech", "company": "BRANE" },
    // { "name": "Anushka Rasure", "Roll_no": "ECE53", "year": "2023", "branch": "MME", "course": "BTech", "company": "VESUVIUS" },
    // // Continue adding entries similarly


    //   { "name": "Aditi Das", "Roll_no": "21ECM1R01", "year": "2023", "branch": "ECE", "course": "BTech", "company": "AMD" },
    //   { "name": "Amit Kumar Thakur", "Roll_no": "21ECM1R02", "year": "2023", "branch": "ECE", "course": "BTech", "company": "Siemens EDA (Mentor Graphics)" },
    //   { "name": "Balwant Kumar Yadav", "Roll_no": "21ECM1R03", "year": "2023", "branch": "ECE", "course": "BTech", "company": "C Dot / Ceremorphic" },
    //   { "name": "Robbi Bhargavi", "Roll_no": "21ECM1R05", "year": "2023", "branch": "ECE", "course": "BTech", "company": "AMD" },
    //   { "name": "Daya Sagar Tummala", "Roll_no": "21ECM1R07", "year": "2023", "branch": "ECE", "course": "BTech", "company": "HoneyWell" },
    //   { "name": "Jotirmayee Ghosh", "Roll_no": "21ECM1R09", "year": "2023", "branch": "ECE", "course": "BTech", "company": "Analog Devices" },
    //   { "name": "Jyoti Sahu", "Roll_no": "21ECM1R10", "year": "2023", "branch": "ECE", "course": "BTech", "company": "VECV" },
    //   { "name": "Indraganti Naga Himanshu", "Roll_no": "21ECM1R12", "year": "2023", "branch": "ECE", "course": "BTech", "company": "Analog Devices" },
    //   { "name": "Naga Surya Manikanta Talla", "Roll_no": "21ECM1R13", "year": "2023", "branch": "ECE", "course": "BTech", "company": "AMD" },
    //   { "name": "Piyush Pal", "Roll_no": "21ECM1R15", "year": "2023", "branch": "ECE", "course": "BTech", "company": "NXP" },
    //   { "name": "Rahul Dabur", "Roll_no": "21ECM1R16", "year": "2023", "branch": "ECE", "course": "BTech", "company": "Samsung Electronics" },
    //   { "name": "Rahul T.", "Roll_no": "21ECM1R17", "year": "2023", "branch": "ECE", "course": "BTech", "company": "Ceremorphic" },
    //   { "name": "Ramireddy Manasa", "Roll_no": "21ECM1R18", "year": "2023", "branch": "ECE", "course": "BTech", "company": "BEL / NXP" },
    //   { "name": "Sai Mounish Nuka", "Roll_no": "21ECM1R20", "year": "2023", "branch": "ECE", "course": "BTech", "company": "AMD" },
    //   { "name": "Sigasarapu Tharun Bhaskar", "Roll_no": "21ECM1R22", "year": "2023", "branch": "ECE", "course": "BTech", "company": "Microchip" },
    //   { "name": "Sujay Mandal", "Roll_no": "21ECM1R24", "year": "2023", "branch": "ECE", "course": "BTech", "company": "Mahindra and Mahindra" },
    //   { "name": "Sitaram Thripurala", "Roll_no": "21ECM1R25", "year": "2023", "branch": "ECE", "course": "BTech", "company": "NXP" },
    //   { "name": "Shivani Sharma", "Roll_no": "21ECM1S27", "year": "2023", "branch": "ECE", "course": "BTech", "company": "Marvell" },
    //   { "name": "Athrav Sapre", "Roll_no": "21ECM1S28", "year": "2023", "branch": "ECE", "course": "BTech", "company": "Idea Forge" },
    //   { "name": "Shriyanshi Kapoor", "Roll_no": "21ECM1S30", "year": "2023", "branch": "ECE", "course": "BTech", "company": "Analog Devices Inc." },
    //   { "name": "Bhukya Vishal", "Roll_no": "21ECM2R01", "year": "2023", "branch": "ECE", "course": "BTech", "company": "BEL" },
    //   { "name": "Chaitanya Reddy", "Roll_no": "21ECM2R02", "year": "2023", "branch": "ECE", "course": "BTech", "company": "AMD" },
    //   { "name": "Chandravardhan Bantu", "Roll_no": "21ECM2R03", "year": "2023", "branch": "ECE", "course": "BTech", "company": "AMD" },
    //   { "name": "Gantasala Naga Lahari", "Roll_no": "21ECM2R05", "year": "2023", "branch": "ECE", "course": "BTech", "company": "AMD" },
    
    
    
  // { "name": "Budumuru Rohit Kumar", "Roll_no": "21MEM2R04", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Micron" },
  // { "name": "K.V.Harishankar", "Roll_no": "21MEM2R07", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Novartis" },
  // { "name": "Tejasvi Sanjay", "Roll_no": "21MEM2R22", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Collins Aerospace" },
  // { "name": "Chiluveri Kishore", "Roll_no": "21MEM2R09", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Tata Motors" },
  // { "name": "B. Basu Majumder", "Roll_no": "21MEM2R03", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Tata Motors" },
  // { "name": "Ranjith Roopak S R", "Roll_no": "21MEM2R16", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Tata Motors" },
  // { "name": "Apurv alok vardhan", "Roll_no": "21MEM2R02", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Hexagon Capability Center Ltd." },
  // { "name": "Gopal Kumar Saxena", "Roll_no": "21MEM2R05", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "HCL Tech" },
  // { "name": "Lavesh Kumar", "Roll_no": "21MEM2R10", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "HCL Tech" },
  // { "name": "C Anupama", "Roll_no": "21MEM2S24", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Fluence Energy" },
  // { "name": "Raj kumar yadav", "Roll_no": "21MEM2R15", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "FIITJEE" },
  // { "name": "Mohammad Addeb Khan", "Roll_no": "21MEM2R11", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Tata Motors" },
  // { "name": "Saikrishna Patnaik", "Roll_no": "21MEM2R17", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Aakash Byju's" },
  // { "name": "Kanda Sudhakara Naidu", "Roll_no": "21MEM2R20", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "DEC Industries" },
  // { "name": "Sanju Naskar", "Roll_no": "21MEM2R19", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Fenice Energy" },
  // { "name": "E.Hathi Ram Naik", "Roll_no": "21MEM2R06", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Infosys" },
  // { "name": "Nitheesh kumar A", "Roll_no": "21MEM2R14", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Infosys" },
  // { "name": "Murkar Aman Sudhakar", "Roll_no": "21MEM1R01", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "WabTec" },
  // { "name": "S Ananth Narayan", "Roll_no": "21MEM1R02", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "VECV" },
  // { "name": "Prabhat Kumar Singh", "Roll_no": "21MEM1R16", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "PWC India" },
  // { "name": "Madaka Ramu", "Roll_no": "21MEM1R08", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Collins Aerospace" },
  // { "name": "Sasanka Sekhar K Deka", "Roll_no": "21MEM1R20", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "HCL Tech" },
  // { "name": "Shubhankar Sinha", "Roll_no": "21MEM1R21", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "SISW" },
  // { "name": "Sanjeevi Bharath", "Roll_no": "21MEM1R19", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Cyient" },
  // { "name": "Naveen Kumar", "Roll_no": "21MEM1S25", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Cyient" },
  // { "name": "Harnish Patel", "Roll_no": "21MEM1R15", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "HCL Tech" },
  // { "name": "Arvind Verma", "Roll_no": "21MEM1R03", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "HCL Tech" },
  // { "name": "Parth Chauhan", "Roll_no": "21MEM1R14", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "HCL Tech" },
  // { "name": "Dipanshu Pant", "Roll_no": "21MEM1R05", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Simerics" },
  // { "name": "Mosuru Hari Krishna", "Roll_no": "21MEM1R11", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "MSIL" },
  // { "name": "Yogesh Nogdhe", "Roll_no": "21MEM1R22", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "M&M" },
  // { "name": "Mantu Sahu", "Roll_no": "21MEM1R10", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Siemens Energy" },
  // { "name": "Pankaj Bhoyar", "Roll_no": "21MEM1R13", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Siemens Energy" },
  // { "name": "Nayan Vilhekar", "Roll_no": "21MEM1R12", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Fenice Energy" },
  // { "name": "AKASH KUMAR", "Roll_no": "21MEM1S23", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Fenice Energy" },
  // { "name": "Rathod Kiran", "Roll_no": "21MEM1R17", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Infosys" },
  // { "name": "Pradeep Lama", "Roll_no": "21MEM3R12", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "PWC India" },
  // { "name": "Alok Kumar", "Roll_no": "21MEM3R05", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Collins Aerospace" },
  // { "name": "Abhay Kumar Kesherwani", "Roll_no": "21MEM3R02", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "Hexagon" },
  // { "name": "Shivendra Yadav", "Roll_no": "21MEM3R08", "year": "2023", "branch": "Mechanical", "course": "MTech", "company": "WabTec" }


  
];

 Detail.insertMany(placementData).then(()=>{console.log("query is inserted")}).catch((err)=>{console.log(err)});
  
module.exports=Detail;
